name: Feature Request
description: Suggest a new algorithm or logic enhancement.
title: "[FEATURE] <short description>"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Love CPL? Have an idea for a new function or improvement? Let us know!

  - type: input
    id: feature
    attributes:
      label: Feature description
      placeholder: "What would you like to see added or changed?"
    validations:
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: How will this feature be used?
      placeholder: e.g., “I need `gcd` function to simplify fractions.”
    validations:
      required: true
