name:  Feature request
about: Suggest a new algorithm or enhancement
title: "[FEATURE] short description"
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Love CPL? Have an idea for a new function or improvement? Let us know!

  - type: input
    id: feature
    attributes:
      label: Feature description
      placeholder: “What would you like to see added or changed?”
      required: true

  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: How will this feature be used?
      placeholder: e.g., “I need `gcd` function to simplify fractions.”

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What have you tried so far?
      placeholder: e.g., “Used my own implementation, but it’s too slow.”

  - type: input
    id: priority
    attributes:
      label: Priority (low/medium/high)
      placeholder: “medium”
