name: Question
description: Ask about usage, logic doubts, or implementation help.
title: "[QUESTION] <short description>"
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Got a question about CPL’s functions or logic? Ask away below.

  - type: input
    id: question
    attributes:
      label: Your question
      placeholder: "How do I use `rotateArray` to rotate left by 2?"
    validations:
      required: true
