name:  Question
about: Ask about usage, concepts, or learning resources
title: "[QUESTION] short description"
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about CPL’s functions or logic? Ask away!

  - type: input
    id: question
    attributes:
      label: Your question
      placeholder: “How do I use `rotateArray` to rotate left by 2?”
      required: true
